### ISSUE TITLE
Help File Generator step for Mac?

### ISSUE THREAD

**Issue by mhomol** [gordon-matt/Doxie#3]
Step 5 for getting things going is to Run a Help File Generator.  I'm hoping to use this utility for a .Net Core Assembly I've built.  Is there a command line tool for doing this step on a Mac or am I going to have to run all of this on Windows to get it working?  If Windows, what is the actual command line or executable I should be running to generate the Help Files there?

**Comment by gordon-matt** [comment]
Hi there,

There are 2 versions of the Help File Generator:
```

1. Doxie.HelpFileGenerator.GUI
2. Doxie.HelpFileGenerator.Console
```

Both of these can be found in the source code.

The GUI version will of course only run on Windows. The Console version is written in .NET Core and as such should run on Mac, but I have never tested it - I do not have access to a Mac.

Another important note is that the console version was just slapped together really quickly - I've not had time to polish it off into something more professional where you can pass arguments in. For now, just open the solution in Visual Studio, modify `Program.cs` to tell it the path and the files you want to include.. and run it that way. I know that's not ideal, but it will have to do for now. I will improve the console app when I have the time.

**Comment by mhomol** [comment]
Okay, got it.  That helped me move forward.  I need to try and confirm that my pathing is done correctly for mac - still a little confused there since it's not apparent what an absolute path looks like on Mac.  Regardless, it sounds like the chief responsibility of the console app is to generate the assemblies.json file - so far that is really tiny for me, so I'm wondering if that means that my console app still isn't actually finding the Dll to process.  But once I get a good file, you indicate placing it into Doxie/js.  Where do I find that?

**Comment by mhomol** [comment]
Actually I think I already answered my question about where to place it - didn't realize that there was another Doxie folder for the jspm stuff as well - only noticed the 3 project folders in the Doxie.sln.  How difficult will it be for me to get that site running from a Mac?

**Comment by mhomol** [comment]
sorry for typing as I'm going through all of this.  Part of this may be that I'm new to jspm - I tried loading Doxie in Visual Studio Code, thinking I could execute it as a Node.js site, but I guess that's not what this is?

**Comment by gordon-matt** [comment]
A couple of notes for you:

1. It seems JSPM has a new version since I created Doxie. To prevent any weird errors when installing JSPM packages, uninstall your version with:

`npm uninstall -g jspm`

Then install the specific version:

`npm install -g jspm@0.16.55`

If you have a *jspm_packages* directory from using the newer JSPM, then delete it..

Then you run `jspm install` again.

2. When running `gulp bundle`, make sure to open the *config.js* and change your *baseURL* to this:

`baseURL: "/"`
(I assume it's the same on Mac)

3. If the above runs fine, you should get a new file, as follows: */dist/aurelia-build.js*

4. Now deploy to a web server. I used IIS, but you'll have to use something else.. or you can deploy to GitHub pages as well, but remember to change the *baseURL* once again to match the path of your deployed application.

If all else fails (having a hard time getting it working), then just clone my gh-pages Doxie site that I created for my other project called Extenso. You can find it here:

[Extenso](https://github.com/gordon-matt/Extenso/)

Clone that and switch to the *gh-pages* branch, then copy and paste the files to wherever you want and just change the logo, the CSS (if you want), the footer and of course the help file.

Let me know if this helps.

Good luck.
